name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Build
      run: |
        npm install
        npm run build
  
  sync-branch:
    if: github.event_name == 'push'
    needs: [ build ]    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Push changes to heroku branch
        uses: PeerSocial-io/push@master
        with:
          github_token: ${{ github.token }}
          branch: heroku
          force: true
